import StyleDictionary from 'style-dictionary';

const kebab = (str) =>
  String(str)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();

const stripLayer = (segment) => segment !== 'primitive' && segment !== 'semantic';

const kernName = (path) => 'kern-' + path.filter(stripLayer).map(kebab).join('-');

StyleDictionary.registerTransform({
  name: 'name/kern',
  type: 'name',
  transform: (token) => kernName(token.path),
});

StyleDictionary.registerFormat({
  name: 'kern/tailwind-preset',
  format: ({ dictionary }) => {
    const preset = {
      colors: {},
      spacing: {},
      fontFamily: {},
      fontSize: {},
      fontWeight: {},
      lineHeight: {},
      letterSpacing: {},
      borderRadius: {},
      boxShadow: {},
    };
    const tailwindKeyForTypography = {
      fontFamily: 'fontFamily',
      fontSize: 'fontSize',
      fontWeight: 'fontWeight',
      lineHeight: 'lineHeight',
      letterSpacing: 'letterSpacing',
    };
    for (const token of dictionary.allTokens) {
      const cssVar = `var(--${token.name})`;
      const top = token.path[0];
      const path = token.path.filter(stripLayer);
      if (top === 'color') {
        const key = path.slice(1).map(kebab).join('-');
        preset.colors[key] = cssVar;
      } else if (top === 'spacing') {
        preset.spacing[path.slice(1).join('-')] = cssVar;
      } else if (top === 'radius') {
        preset.borderRadius[path.slice(1).join('-')] = cssVar;
      } else if (top === 'shadow') {
        preset.boxShadow[path.slice(1).join('-')] = cssVar;
      } else if (top === 'typography') {
        const tailwindKey = tailwindKeyForTypography[token.path[1]];
        if (tailwindKey) {
          const key = path.slice(2).map(kebab).join('-');
          preset[tailwindKey][key] = cssVar;
        }
      }
    }
    const body = JSON.stringify(preset, null, 2).replace(/\n/g, '\n    ');
    return [
      '// AUTO-GENERATED by scripts/build-tokens.mjs — DO NOT EDIT.',
      '// Tailwind preset: values reference CSS custom properties from build/css/variables.css.',
      '',
      'export default {',
      '  theme: {',
      `    extend: ${body}`,
      '  },',
      '};',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'kern/ts-tokens',
  format: ({ dictionary }) => {
    const root = {};
    for (const token of dictionary.allTokens) {
      const path = token.path.filter(stripLayer);
      let cursor = root;
      for (let i = 0; i < path.length - 1; i++) {
        if (typeof cursor[path[i]] !== 'object' || cursor[path[i]] === null) {
          cursor[path[i]] = {};
        }
        cursor = cursor[path[i]];
      }
      cursor[path[path.length - 1]] = token.$value ?? token.value;
    }
    const body = JSON.stringify(root, null, 2);
    return [
      '// AUTO-GENERATED by scripts/build-tokens.mjs — DO NOT EDIT.',
      '// Typed token catalog with resolved values (semantic aliases dereferenced).',
      '',
      `export const tokens = ${body} as const;`,
      '',
      'export type Tokens = typeof tokens;',
      '',
    ].join('\n');
  },
});

export default {
  source: ['tokens/**/*.json'],
  usesDtcg: true,
  log: { warnings: 'warn', verbosity: 'default' },
  platforms: {
    css: {
      transforms: ['attribute/cti', 'name/kern'],
      buildPath: 'build/css/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            selector: ':root',
            outputReferences: false,
          },
        },
      ],
    },
    ts: {
      transforms: ['attribute/cti', 'name/kern'],
      buildPath: 'build/ts/',
      files: [
        {
          destination: 'tokens.ts',
          format: 'kern/ts-tokens',
        },
      ],
    },
    tailwind: {
      transforms: ['attribute/cti', 'name/kern'],
      buildPath: 'build/tailwind/',
      files: [
        {
          destination: 'preset.js',
          format: 'kern/tailwind-preset',
        },
      ],
    },
  },
};
